main: creeperconfetti.CreeperConfettiPro
name: CreeperConfettiPro
author: Nice_Cam_
version: 2.1-bukkit
api-version: 1.21

commands:
  creeperconfetti:
    description: CreeperConfettiPro 主命令 / Main command for CreeperConfettiPro
    usage: /creeperconfetti <reload | reseteffect | seteffect | reloadlanguage | setlanguage | language>
    permission: creeperconfetti.command
    aliases: [cc, confetti]

permissions:
  creeperconfetti.command:
    description: 允许使用 CreeperConfettiPro 命令 / Allows using CreeperConfettiPro commands
    default: op